import { Link } from "react-router-dom";
import { motion } from "motion/react";
import { ArrowRight, ClipboardCheck, Landmark, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button.tsx";

export function LandingOperations() {
  return <><section className="relative overflow-hidden py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div className="clay p-6 sm:p-8"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-primary/12 text-primary"><Landmark size={21} /></span><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-primary">Operational clarity</p><p className="mt-1 text-sm text-muted-foreground">Structured around platform processes</p></div></div><div className="mt-8 space-y-3"><StatusRow icon={ClipboardCheck} title="Membership payment review" text="Plan payments are reviewed before plan activation." /><StatusRow icon={ShieldCheck} title="Managed withdrawal requests" text="Withdrawals are managed according to the platform's existing processes and rules." /></div></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Clarity at every step</p><h2 className="mt-4 text-3xl font-black tracking-[-0.04em] sm:text-4xl">Know what you&apos;re managing and where to find it.</h2><p className="mt-5 max-w-xl text-base leading-7 text-muted-foreground">Valtora gives members a place to follow plan status, network activity, commissions and withdrawal requests. Each action follows the platform&apos;s established review and operational processes.</p></div></div></section><section className="pb-20 sm:pb-28"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.3 }} className="clay relative overflow-hidden border-primary/25 px-6 py-10 sm:px-10 sm:py-12"><div className="pointer-events-none absolute -right-16 -top-24 size-72 rounded-full border border-primary/20" /><div className="pointer-events-none absolute -bottom-32 right-20 size-64 rounded-full bg-primary/10 blur-3xl" /><div className="relative flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Start with confidence</p><h2 className="mt-4 text-3xl font-black tracking-[-0.04em] sm:text-4xl">A clearer way to build your Valtora network.</h2><p className="mt-4 text-base leading-7 text-muted-foreground">Create an account, review available memberships and follow your activity from one focused dashboard.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 rounded-xl px-6"><Link to="/register">Join Valtora <ArrowRight size={16} /></Link></Button><Button asChild size="lg" variant="secondary" className="h-12 rounded-xl px-6"><a href="#plans">View plans</a></Button></div></div></motion.div></div></section></>;
}
function StatusRow({ icon: Icon, title, text }: { icon: typeof ClipboardCheck; title: string; text: string }) { return <div className="clay-sm flex gap-3 p-4"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon size={17} /></span><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div></div>; }
